
const DB_NAME='3dcd_ecosistema_respaldos_v1',STORE='backups';
const $=s=>document.querySelector(s);let items=[];
function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const st=db.createObjectStore(STORE,{keyPath:'id'});st.createIndex('appId','appId',{unique:false});st.createIndex('createdAt','createdAt',{unique:false})}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbAll(){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>{const v=r.result||[];db.close();res(v)};r.onerror=()=>{const e=r.error;db.close();rej(e)}})}
async function dbPut(v){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v);tx.oncomplete=()=>{db.close();res(v)};tx.onerror=()=>{const e=tx.error;db.close();rej(e)}})}
async function dbDelete(id){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>{const e=tx.error;db.close();rej(e)}})}
async function dbClear(){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>{const e=tx.error;db.close();rej(e)}})}
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function fmtDate(v){const d=new Date(v);return Number.isNaN(d)?'—':new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function fmtSize(n){n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(n>10485760?0:1)+' MB'}
function slug(s){return String(s||'aplicacion').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'aplicacion'}
function groups(){const m=new Map();for(const x of items){const k=x.appId||'otros';if(!m.has(k))m.set(k,{appId:k,appName:x.appName||'Otros',appUrl:x.appUrl||'',rows:[]});const g=m.get(k);if(x.appUrl)g.appUrl=x.appUrl;g.rows.push(x)}for(const g of m.values())g.rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return [...m.values()].sort((a,b)=>a.appName.localeCompare(b.appName,'es'))}
function render(){const gs=groups();$('#appsCount').textContent=gs.length;$('#backupCount').textContent=items.length;$('#totalSize').textContent=fmtSize(items.reduce((a,b)=>a+Number(b.size||b.blob?.size||0),0));const box=$('#folders');if(!gs.length){box.innerHTML='<div class="empty"><b>Todavía no hay respaldos</b>Desde Gestor tocá “Guardar en Respaldos” y aparecerá acá automáticamente. También podés agregar un ZIP con el botón +.</div>';return}box.innerHTML=gs.map(g=>{const sz=g.rows.reduce((a,b)=>a+Number(b.size||b.blob?.size||0),0),last=g.rows[0];return `<section class="folder" data-app="${esc(g.appId)}"><div class="folderHead"><div class="folderIcon">▰</div><div class="folderText"><h3>${esc(g.appName)}</h3><p>Último: ${esc(fmtDate(last.createdAt))} · ${esc(fmtSize(sz))}</p></div><div class="folderCount">${g.rows.length}</div></div><div class="folderActions"><button class="folderBtn open" data-act="toggle">Ver respaldos</button><button class="folderBtn download" data-act="download-app">ZIP carpeta</button></div><div class="backups">${g.rows.map(x=>`<div class="backup" data-id="${esc(x.id)}"><div class="backupTop"><div><div class="backupName">${esc(x.fileName||'respaldo.zip')}</div><div class="backupMeta">${esc(fmtDate(x.createdAt))} · ${esc(fmtSize(x.size||x.blob?.size||0))}</div></div></div><div class="backupActions">${x.appUrl?'<button class="smallBtn restore" data-act="restore">Abrir en '+esc(g.appName)+'</button>':''}<button class="smallBtn" data-act="download">Descargar</button><button class="smallBtn danger" data-act="delete">Eliminar</button></div></div>`).join('')}</div></section>`}).join('')}
async function refresh(){try{items=await dbAll();render()}catch(e){console.error(e);alert('No se pudieron leer los respaldos de este navegador.')}}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
let crcTable=null;function crc32(bytes){if(!crcTable){crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xEDB88320^(c>>>1)):(c>>>1);crcTable[n]=c>>>0}}let c=0xFFFFFFFF;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xFFFFFFFF)>>>0}function u16(n){return new Uint8Array([n&255,(n>>>8)&255])}function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}function concat(parts){const len=parts.reduce((a,b)=>a+b.length,0),o=new Uint8Array(len);let p=0;for(const b of parts){o.set(b,p);p+=b.length}return o}
function zipStore(files){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const f of files){const name=enc.encode(f.name),data=f.data,crc=crc32(data),local=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);centrals.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length}const cd=concat(centrals),end=concat([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(offset),u16(0)]);return new Blob([...locals,cd,end],{type:'application/zip'})}
async function zipFor(rows,prefix=''){const fs=[];for(const x of rows){if(!x.blob)continue;fs.push({name:prefix+(x.fileName||'respaldo.zip'),data:new Uint8Array(await x.blob.arrayBuffer())})}if(!fs.length)throw new Error('Sin archivos');return zipStore(fs)}
function stamp(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}`}
async function downloadAll(){if(!items.length)return alert('Todavía no hay respaldos.');const fs=[];for(const g of groups())for(const x of g.rows)if(x.blob)fs.push({name:`${slug(g.appName)}/${x.fileName||'respaldo.zip'}`,data:new Uint8Array(await x.blob.arrayBuffer())});downloadBlob(zipStore(fs),`respaldos-3dcd-${stamp()}.zip`)}
function guessApp(file){const n=file.name.toLowerCase();if(n.includes('gestor')||n.includes('recibidos'))return ['gestor','Gestor'];return ['otros','Otros']}
async function importFile(file){let [appId,appName]=guessApp(file);if(appId==='otros'){const v=prompt('¿De qué aplicación es este respaldo?','Otra aplicación');if(v===null)return;appName=v.trim()||'Otra aplicación';appId=slug(appName)}const blob=file.slice(0,file.size,file.type||'application/octet-stream');await dbPut({id:appId+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),appId,appName,appUrl:'',createdAt:new Date().toISOString(),fileName:file.name||'respaldo.zip',mime:file.type||'',size:file.size,blob,formatVersion:1,manual:true});await refresh()}
$('#folders').onclick=async e=>{const act=e.target.closest('[data-act]')?.dataset.act;if(!act)return;const folder=e.target.closest('.folder'),id=e.target.closest('.backup')?.dataset.id,g=groups().find(x=>x.appId===folder?.dataset.app);if(act==='toggle'){folder.classList.toggle('expanded');e.target.textContent=folder.classList.contains('expanded')?'Ocultar':'Ver respaldos';return}if(act==='download-app'&&g){const b=await zipFor(g.rows,slug(g.appName)+'/');downloadBlob(b,`${slug(g.appName)}-respaldos-${stamp()}.zip`);return}const x=items.find(v=>v.id===id);if(!x)return;if(act==='download')downloadBlob(x.blob,x.fileName||'respaldo.zip');if(act==='delete'){if(confirm('¿Eliminar este respaldo?')){await dbDelete(x.id);await refresh()}}if(act==='restore'){if(!x.appUrl)return alert('Este respaldo fue agregado manualmente y no tiene una aplicación vinculada.');const u=new URL(x.appUrl);u.searchParams.set('restoreBackup',x.id);location.href=u.href}};
function chooseFile(){$('#fileInput').click()}$('#addBtn').onclick=chooseFile;$('#importBtn').onclick=chooseFile;$('#menuImport').onclick=()=>{menu.classList.remove('show');chooseFile()};$('#fileInput').onchange=async e=>{const f=e.target.files?.[0];e.target.value='';if(f)try{await importFile(f)}catch(err){console.error(err);alert('No se pudo agregar ese respaldo.')}};
$('#downloadAllBtn').onclick=downloadAll;$('#menuDownload').onclick=()=>{menu.classList.remove('show');downloadAll()};$('#menuRefresh').onclick=()=>{menu.classList.remove('show');refresh()};$('#menuClear').onclick=async()=>{menu.classList.remove('show');if(!items.length)return;if(confirm(`¿Eliminar los ${items.length} respaldos guardados en esta central?`)){await dbClear();await refresh()}};
const menu=$('#menu');$('#menuBtn').onclick=()=>menu.classList.toggle('show');document.addEventListener('click',e=>{if(!menu.contains(e.target)&&e.target!==$('#menuBtn'))menu.classList.remove('show')});window.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('pageshow',refresh);refresh();
